services:
  - type: web
    name: scoringclients-api
    env: docker
    plan: free
    dockerfilePath: ./api/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: THRESHOLD
        value: "0.402"
      - key: INPUT_COLUMNS_PATH
        value: data/input_columns.json
      - key: CLIENTS_CSV_PATH
        value: data/clients_sample.csv

  - type: web
    name: scoringclients-streamlit
    env: docker
    plan: free
    dockerfilePath: ./streamlit.Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: STREAMLIT_API_BASE_URL
        value: https://scoringclients.onrender.com
      - key: STREAMLIT_CLIENTS_CSV
        value: /app/api/data/clients_sample.csv
