services:
  - type: web
    name: scoringclients-api
    env: docker
    plan: free
    dockerfilePath: ./api/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: THRESHOLD
        value: "0.402"
      - key: INPUT_COLUMNS_PATH
        value: data/input_columns.json
      - key: CLIENTS_CSV_PATH
        value: data/clients_sample.csv

  - type: web
    name: scoringclients-dashboard
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install -r "Projet dashboard/requirements.txt"
    startCommand: streamlit run "Projet dashboard/app_dashboard.py" --server.port=$PORT --server.address=0.0.0.0
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DASHBOARD_API_URL
        value: https://scoringclients-api.onrender.com
